// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clinics_api.Contexts;

namespace clinics_api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211219230616_Clinic")]
    partial class Clinic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("clinics_api.Models.Client", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Cpf");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("clinics_api.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("clinics_api.Models.Scheduling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientCpf")
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExamIds")
                        .HasColumnType("longtext");

                    b.Property<string>("Exams")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("FinalDate")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("InitialDate")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCpf");

                    b.ToTable("Schedulings");
                });

            modelBuilder.Entity("clinics_api.Models.Client", b =>
                {
                    b.OwnsOne("clinics_api.Models.Address", "AddressObject", b1 =>
                        {
                            b1.Property<string>("ClientCpf")
                                .HasColumnType("varchar(11)");

                            b1.Property<string>("City")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("District")
                                .HasColumnType("longtext");

                            b1.Property<string>("Num")
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)");

                            b1.Property<string>("State")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Street")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(9)
                                .HasColumnType("varchar(9)");

                            b1.HasKey("ClientCpf");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientCpf");
                        });

                    b.Navigation("AddressObject");
                });

            modelBuilder.Entity("clinics_api.Models.Scheduling", b =>
                {
                    b.HasOne("clinics_api.Models.Client", "Client")
                        .WithMany("Schedulings")
                        .HasForeignKey("ClientCpf");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("clinics_api.Models.Client", b =>
                {
                    b.Navigation("Schedulings");
                });
#pragma warning restore 612, 618
        }
    }
}
